services:
  postgres:
    image: postgres:14.20-alpine3.23
    container_name: fastfood_customer_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - fastfood-customer-network

networks:
  fastfood-customer-network:
    driver: bridge
