apiVersion: v1
kind: Service
metadata:
  name: fastfood-customer-api
  namespace: fiap
  labels:
    app: fastfood-customer-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-aks-prod"
    service.beta.kubernetes.io/azure-load-balancer-ip: "aks-fiap-soat-prod-service-ip"
spec:
  type: LoadBalancer  
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: fastfood-customer-api